version: '2'

networks:
  ttn_docker_network:
    driver: bridge

services:

  influxdb:
    image: arm32v7/influxdb:latest
    volumes:
      - /home/pi/lora_mgr_project/influx/influx_data:/var/lib/influxdb
      - /home/pi/lora_mgr_project/influx/influxdb.conf:/etc/influxdb/influxdb.conf
    networks:
      - ttn_docker_network

  data_downloader:  
    build: ./data_downloader
    volumes:
      - /home/pi/lora_mgr_project/data_downloader:/data_downloader
    networks:
      - ttn_docker_network
    ports:
      - "65432:65432"
